### ISSUE TITLE
lines <l/>

### ISSUE THREAD

**Issue by gcelano** [OpenGreekAndLatin/First1KGreek#1099]
I see (in this repo and/or CanonicalGreek) that not all lines in poetry have @n. This is probably due to the fact that in the print edition not all lines are numbered. However, when it comes to extracting information, having numbers for all lines would be extremely helpful

**Comment by lcerrato** [comment]
Line numbers are being added as we convert primary texts in the canonical repos.

**Comment by gcelano** [comment]
is it possible to easily add @n to all lines in our current pipeline or does it require a new script?

**Comment by lcerrato** [comment]
There is a transform but it does not work well for all types of works so it requires editorial review. Anything that does not have numbering on every line is getting numbering on every line as part of my workflow.

**Comment by sonofmun** [comment]
This script works pretty well: https://github.com/PerseusDL/tei-conversion-tools/blob/master/xslt/line_numbering_looping.xsl
Make sure to read the instructions on "HOW TO USE" in lines 18-24.

**Comment by gcelano** [comment]
Thanks @lcerrato!

**Comment by gcelano** [comment]
I have queried the repos and found documents with this problem only in CanonicalGreek. I will open an issue there.
