### ISSUE TITLE
tlg2018.tlg002.opp-grc3 contains both Greek and English work

### ISSUE THREAD

**Issue by AlisonBabeu** [OpenGreekAndLatin/First1KGreek#1149]
The XML file for tlg2018.tlg002.opp-grc3 contains the entire text of the digitized volume it appears, including the preface, the Greek text and English translation, and the index, so I believe in order to be cts-compliant @sonofmun, the English text will need to be put into its own file. I did fix the header for this file however per pull request #1147

**Comment by sonofmun** [comment]
Copy of issue #716
