### ISSUE TITLE
Wrong Gorgias identified-need to change tlg2255 to tlg0593

### ISSUE THREAD

**Issue by AlisonBabeu** [OpenGreekAndLatin/First1KGreek#1272]
Two fragmentary works by Gorgias of Leontini (tlg2255.perseus001 and tlg2255.perseus002) were incorrectly assigned to the textgroup tlg2255 (Gorgias Atheniensis-a fragmentary historian). The textgroup for Gorgias of Leontini  is tlg0593. Both of these two works were included under one ID in the TLG tlg0593.tlg003 and were thus cataloged together under that [work ID](http://catalog.perseus.org/catalog/urn:cts:greekLit:tlg0593.tlg003.opp-grc1). 

While I know that we are not following strictly along the lines of TLG IDS, in this case I would like to change the textgroup ID for these files since we have texts by both of the authors in the Perseus Catalog and in the OGL collection (assuming that the text of TLG 2255 is in the 
[DFGH](http://www.dfhg-project.org/DFHG/digger.php?what%5B%5D=author%7CGORGIAS+ATHENIENSIS&onoffswitch=on))

I'm not entirely certain what to do here @sonofmun, however, in terms of numbering the two works. Shall I go with tlg0593.perseus001 and tlg0593.perseus002 for consistency, since we have chosen to separate out the two works in Fragmenta?

**Comment by sonofmun** [comment]
Instead of perseus001, I would do 1st1K001 and 1st1K002 or perhaps ogl001 and ogl002. But I don't think it really matters what we assign as long as it is unique to this work.

**Comment by AlisonBabeu** [comment]
O.k. I'll go with tlg0593.1st1K001 and tlg05931st1K002.

**Comment by AlisonBabeu** [comment]
So @sonofmun I hope I did this right, I will wait for feedback before I do a second textgroup rename that is needed, see issue #984

**Comment by sonofmun** [comment]
I made a couple of additions (respStmt), but otherwise it looks good.

**Comment by AlisonBabeu** [comment]
Sweet!
