### ISSUE TITLE
tlg4015.tlg003.opp-grc1 should be tlg4015.tlg004.opp.grc.1

### ISSUE THREAD

**Issue by AlisonBabeu** [OpenGreekAndLatin/First1KGreek#1530]
So the wrong ID and work title were used for this work. They were put under tlg4013.tlg003 which is In Aristotelis analytica posteriora commentaria (prooemium e codd. BRL) , whereas this file contains the entire work of tlg4013.tlg004 (In Aristotelis analytica posteriora commentaria ). I would like to renumber this work and fix the metadata according so it corresponds with the entry in the Perseus Catalog.

I assume @sonofmun  that I may go ahead with changing these files in my fork and then sending then on in a pull request.

**Comment by sonofmun** [comment]
Yes, please go ahead and do that, @AlisonBabeu

**Comment by annettegessner** [comment]
I guess this issue can be closed.
