### ISSUE TITLE
Typographical errors in tlg1799.tlg007/8

### ISSUE THREAD

**Issue by Pria20** [OpenGreekAndLatin/First1KGreek#1546]

**Comment by Pria20** [comment]
As a note, this text included qoppa's in the numbering system. The computer wasn't able to recognize the characters and had represented each usage as "??" Similarly, in another file I found that digammas were represented by the computer as "??"

I can create these symbols using the greek polytonic keyboard on a Mac (**option+q** = ϙ **option+z** = ϟ) but it was rather tedious. Has this issue been seen before and is there a more efficient way to address these missing symbols? @sonofmun @annettegessner

**Comment by annettegessner** [comment]
Hi Pria! Thanks for bringing this to our attention! I cannot remember any case of not being able to identify those symbols. If this keeps occurring, we have to find a way to prevent it.

**Comment by annettegessner** [comment]
Also see #1544

**Comment by djwhittle** [comment]
Hello I am a CHS intern, I am working on this if no one is already

**Comment by djwhittle** [comment]
@AlisonBabeu @sonofmun @annettegessner Currently working through the in text corrections for tlg12799.tlg008, within this file there is a figure (an acute angle triangle with the hypotenuse drawn). Are there any epidoc conventions for how to structure this within the xml file?

**Comment by sonofmun** [comment]
@djwhittle See #251.

**Comment by djwhittle** [comment]
I checked out #251 but I am still unsure how to indicate the position of the figure within the text, the figure found here (http://www.archive.org/stream/euclidisoperaomn06eucluoft#page/202/mode/2up), is placed to the right hand side of the text rather than being below or in between text. How can I indicate this in the file?

**Comment by lcerrato** [comment]
fixed via #2093
