### ISSUE TITLE
tlg4019.tlg001.opp-grc1 also contains the text of tlg4019.tlg002

### ISSUE THREAD

**Issue by AlisonBabeu** [OpenGreekAndLatin/First1KGreek#1559]
The file tlg4019.tlg001.opp-grc1, the Prolegomena of Olympiodorus, also contains the full text of work tlg4019.tlg002, In Aristotelis categorias commentarium .

The work in question starts at [line 1221](https://github.com/OpenGreekAndLatin/First1KGreek/blob/master/data/tlg4019/tlg001/tlg4019.tlg001.opp-grc1.xml#L1221) in the file (at page 26) and continues until the end of the file. This work will need to be separated out and given its own XML file with corresponding CTS xml files and header correction.

**Comment by LindaMcNulty** [comment]
I can work on this one!

**Comment by sonofmun** [comment]
Corrected with #1661
