### ISSUE TITLE
tlg4024.tlg001.opp-grc2 also contains the Latin translation

### ISSUE THREAD

**Issue by AlisonBabeu** [OpenGreekAndLatin/First1KGreek#1568]
[tlg4024.tlg001.opp-grc2](https://github.com/OpenGreekAndLatin/First1KGreek/blob/master/data/tlg4024/tlg001/tlg4024.tlg001.opp-grc2.xml)

The Historiae by Agathias Scholasticus, also contains the Latin translation of this work. I believe this means @sonofmun we need to split out the translation into the separate file. I did fix the header and other issues with the file via #1567

**Comment by Pria20** [comment]
I can work on this one :)
