### ISSUE TITLE
Two copies of urn:cts:greekLit:tlg4034.tlg003 and urn:cts:greekLit:tlg4034.tlg006

### ISSUE THREAD

**Issue by AlisonBabeu** [OpenGreekAndLatin/First1KGreek#1578]
So @sonofmun  and @annettegessner I'm not entirely certain what to do in terms of the files I found for two works of Michael Ephesius. For both the works [tlg4034.tlg003](https://github.com/OpenGreekAndLatin/First1KGreek/tree/master/data/tlg4034/tlg003) and [tlg4034.tlg006](https://github.com/OpenGreekAndLatin/First1KGreek/tree/master/data/tlg4034/tlg006) there are two versions, opp-grc1, and opp-grc2. 

At first I thought there were two different editions of each work, but after doing a diff of the files in Oxygen, it appears that the opp-grc2 are the same editions, just with minor changes in the opp-grc2, such as an updated creative Commons license and a slightly altered xpath statement.
Is there a reason we are keeping both files, it seems that we would only need one XML file and that the URN would be opp-grc1, as the first version?

**Comment by sonofmun** [comment]
@AlisonBabeu It sounds like there should only be one edition for each, opp-grc1. We may have gotten the same edition from two different places (old Perseus stuff and from DDD?)

**Comment by AlisonBabeu** [comment]
It looks like these files were just from old Perseus stuff, not from DDD, since they are not on the picklist. I guess I just want to know which one to keep and edit, and which one to delete! :)

**Comment by sonofmun** [comment]
I think keeping opp-grc1 makes more sense.

**Comment by sonofmun** [comment]
Corrected in PR #1677
