### ISSUE TITLE
Mark as type="commentary", only 1 citation unit in /tlg4102/tlg011/tlg4102.tlg011.opp-grc1.xml

### ISSUE THREAD

**Issue by sonofmun** [OpenGreekAndLatin/First1KGreek#159]

**Comment by annettegessner** [comment]
commentary on another work, cited by numbers on the left side of the scanned pages and on top of the scanned pages (e.g. VII,7)

https://archive.org/stream/catenaegraecorum04cramuoft#page/162/mode/2up

suggestion: use numbering indicated on top op pages to do a segmentation, number either accordingly or chronologically

**Comment by decline93** [comment]
@lmuellner and I will take this one, with the help of the CHS summer interns. 
The commentary seems divided into two levels, the upper one in roman numerals atop the page, the lower in arabic on the left side of the page. So, VII.7, VII.8, VII.9, ...VIII.1, VIII.2, etc. XML includes most of these left numerals (some are missing or have been read incorrectly by OCR: e.g., 8 as Ϛ), but as <lb>, which conflict with the actual line number listed on the righthand side. Correction: to include all lefthand numbers as corresponding segments, and change the xpath accordingly.

**Comment by annettegessner** [comment]
Thanks a lot @decline93 and @lmuellner for the help! It's very much appreciated especially with difficult files like this. Please don't hesitate to ask me or Matt, if you have any questions!

**Comment by brittanyhardy** [comment]
As of now, every set on comments on verses from Romans is structured as:

<div type="textpart" subtype="chapter" n="...">
<div type="textpart" subtype="verse" n="...">
<div type="textpart" subtype="comment" n="verse" corresp="urn:cts:greekLit:tlg0031.tlg006:...">
<p>...</p></div>
<div type="textpart" subtype="comment" n="1" corresp="#...">
<p>...</p></div>
<div type="textpart" subtype="comment" n="2" corresp="#...">
<p>...</p></div>
</div>
</div>

The two first level divs correspond to the roman and arabic numerals in the edition (VII.7, VII.8, etc), citing chapter and verse of Romans, but do we want to enclose the actual cited verse within the third level div here, with subtype="comment" n="verse"? If so, it looks as though this file is already structured correctly. Are there any other conventions for commentaries we should include?

**Comment by sonofmun** [comment]
If we want to be able to retrieve the text of the verse along with all the comments on it, then it needs to be on the same citation level as the comments. That is why we did that here. So I think it is structured correctly. For the discussion on how to handle commentaries (in this case, ancient commentaries that would be qualified as `<ti:edition>` and not modern commentaries that we would file under `<ti:commentary>`), see issue #201.
