### ISSUE TITLE
two ref target in tlg0645.tlg003.perseus-grc2

### ISSUE THREAD

**Issue by annettegessner** [OpenGreekAndLatin/First1KGreek#178]
there are two volumes being the source of this one file

is it ok, to just write
`<ref target="https://archive.org/details/dialogueavectryp01just">Internet Archive</ref>
 <ref target="https://archive.org/details/dialogueavectryp02just">Internet Archive</ref>`
or does this have to be done elseway?

**Comment by sonofmun** [comment]
As long as that is Epidoc compliant, then do it that way.

**Comment by annettegessner** [comment]
doesn't break anything, so let's keep it this way for now - closing issue
