### ISSUE TITLE
The CTS file and the header for tlg2022.tlg060.opp-grc1 

### ISSUE THREAD

**Issue by AlisonBabeu** [OpenGreekAndLatin/First1KGreek#1799]
So I'm opening this issue @sonofmun to suggest a potential change to the CTS file and header for this work by Gregory Nazianzus, that we also have listed under Pseudo-Menander in the header. 

It currently looks like the following:
```xml
  <ti:title xml:lang="eng">Sententiae (corresponds to quotes from Gregory Nazianzen, 
Carmen morale XXX) (Greek)</ti:title>
```
This title format is then repeated for all the other sections that include the title, including in the XML file header. 
```xml
<title xml:lang="mul">Sententiae (corresponds to quotes from Gregory Nazianzen,
 Carmen morale XXX) (Greek)</title>
<author>pseudo-Menander</author>
```

Since this is actually a work by Gregory Nazianzus, but I think we also want to respect the author attribution of Pseudo-Menander from the original Graeco-Arabic project, may I suggest the following changes to the CTS file:

```xml
<ti:work xmlns:ti="http://chs.harvard.edu/xmlns/cts" 
groupUrn="urn:cts:greekLit:tlg2022" xml:lang="grc" urn="urn:cts:greekLit:tlg2022.tlg060">
  <ti:title xml:lang="lat">Sententiae = (Carmen morale XXX) </ti:title>
  <ti:edition urn="urn:cts:greekLit:tlg2022.tlg060.1st1K-grc1" workUrn="urn:cts:greekLit:tlg2022.tlg060">
    <ti:label xml:lang="lat">Sententiae = (Carmen Morale XXX)</ti:label>
    <ti:description xml:lang="mul">pseudo-Menander, Gregory Nazianzus, 
Sententiae= (Carmen morale XXX), Ullmann, Wiesbaden, 1961</ti:description>
  </ti:edition>
</ti:work>
```
And then for the TEI header:
```xml
 <title xml:lang="lat">Sententiae = (Carmen morale XXX)</title>
        <author>pseudo-Menander</author>
   <author>Gregory Nazianzus</author>
<editor role="editor">Manfred Ullmann</editor>
```
It just looks kind of odd the way it is and it was bothering me!: )
I'm also trying to clear up a number of old issues I found as I first went through the repository.

**Comment by sonofmun** [comment]
I agree with all of this. I think that since we are filing it under Gregory of Nazianzus, we should only put "Carmina Moralia", the title of Gregory's work, in the `<ti:title>` element (this describes the work-level URN as opposed to the edition-level URN). We should probably also add a structured-metadata element with an isVersionOf element to actually make this relationship more machine-readable. So I would suggest a metadata file like the following:

```
<ti:work xmlns:cpt="http://capitains.github.io/xmlns" xmlns:dc="http://purl.org/dc/elements/1.1" xmlns:dct="http://purl.org/dc/terms/" xmlns:ti="http://chs.harvard.edu/xmlns/cts"
groupUrn="urn:cts:greekLit:tlg2022" xml:lang="grc" urn="urn:cts:greekLit:tlg2022.tlg060">
  <ti:title xml:lang="lat">Carmina moralia</ti:title>
  <ti:edition urn="urn:cts:greekLit:tlg2022.tlg060.1st1K-grc1" workUrn="urn:cts:greekLit:tlg2022.tlg060">
    <ti:label xml:lang="lat">Sententiae = (Carmen Morale XXX)</ti:label>
    <ti:description xml:lang="mul">pseudo-Menander, Gregory Nazianzus, 
Sententiae= (Carmen morale XXX), Ullmann, Wiesbaden, 1961</ti:description>
    <cpt:structured-metadata>
      <dct:isVersionOf>urn:cts:greekLit:tlg1791.tlg001</dct:dct:isVersionOf>
      <dct:isVersionOf>urn:cts:greekLit:tlg0541.tlg042</dct:dct:isVersionOf>
    </cpt:structured-metadata>
  </ti:edition>
</ti:work>
```

**Comment by AlisonBabeu** [comment]
Thanks for the further feedback, I will use the cts file above and also update the header.

**Comment by AlisonBabeu** [comment]
So @sonofmun can I close this one?

**Comment by sonofmun** [comment]
Yes. Please do.
