### ISSUE TITLE
tlg0099-This textgroup is Strabo not Anonymous

### ISSUE THREAD

**Issue by AlisonBabeu** [OpenGreekAndLatin/First1KGreek#1942]
So quick question for @ChiaraPalladino and @sonofmun here. I know that this particular text in the First1K is the Chrestomathia, a now accepted anonymous authored text that is also "part" of Strabo's larger geography.

The problem is that the CTS textgroup file [here](https://github.com/OpenGreekAndLatin/First1KGreek/blob/master/data/tlg0099/__cts__.xml) lists Anonymous, so I'm thinking I should probably change this to Strabo, as this is his textgroup ID in Perseus, the Perseus Catalog, etc. It looks like the CTS file for the edition thoroughly explains what the text is, so I'm thinking this shouldn't confuse things to much, but am looking for thoughts before I change it and submit a pull request.

**Comment by sonofmun** [comment]
I agree with you on this. The author that we have should match the URN under which it is classified.

**Comment by ChiaraPalladino** [comment]
It depends on what you list as author. Scholia and Paraphrases are generally listed under anonymous (or by the same title of the work), and Chrestomathiae are close to that type of text. 

The best way to do it would be to have "Chrestomathiae Strabonis" as the title of the work, and "Anonymous" as the author. But I don't have anything against listing it as Strabo's, basically everyone who's looking for that work knows what it is.

**Comment by AlisonBabeu** [comment]
Thanks for the feedback. I'm going to change the CTS top level file to Strabo, but I wasn't planning to change any of the edition level metadata or the edition level CTS file, I think that works as Chiara has described it.
