### ISSUE TITLE
tlg0081.tlg007-two works in one file

### ISSUE THREAD

**Issue by AlisonBabeu** [OpenGreekAndLatin/First1KGreek#2117]
There are two works in the [file](https://github.com/OpenGreekAndLatin/First1KGreek/blob/master/data/tlg0081/tlg007/tlg0081.tlg007.1st1K-grc1.xml) not just one.

tlg0081.tlg006-De Demosthenis dictione, is pages 127-252
tlg0081.tlg007-Libri secundi de antiquis oratoribus reliquiae-is pages 253-254.

I will split the file and add the second work to the repository.

**Comment by lcerrato** [comment]
fixed in #2118
