### ISSUE TITLE
(tlg0544.tlg001.opp-grc1.xml) correct reading οἷον > ἵπποι in 3.18

### ISSUE THREAD

**Issue by nevenjovanovic** [OpenGreekAndLatin/First1KGreek#2128]
The text at [tlg0544.tlg001.opp-grc1.xml](https://github.com/OpenGreekAndLatin/First1KGreek/blob/master/data/tlg0544/tlg001/tlg0544.tlg001.opp-grc1.xml) 3.18 (can be seen at <https://scaife-cts.perseus.org/api/cts?request=GetPassage&urn=urn:cts:greekLit:tlg0544.tlg001.opp-grc1:3.18>) reads:
```xml
ὡς ἔτυχεν ἂν ἦν μὴ οὔσης αἰτίας. οἷον οἷον μὲν ἐκ <lb n="15"/>
μυῶν, εἰ τύχοι, γεννηθήσονται, ἐλέφαντες δὲ ἐκ μυρμήκων·
```
`οἷον οἷον` seems to be an error; Sextus Empiricus' text at this location reads `οἷον ἵπποι`. The reading is ἵπποι  in the source listed in the TEI Header of the XML, cf. its p. 138 on archive.org: <https://archive.org/details/rsoperarecensuit01sextuoft/page/138>.

**Comment by nevenjovanovic** [comment]
Also, a smaller correction is needed in the preceding paragraph, 3.17, of the same text <https://scaife-cts.perseus.org/api/cts?request=GetPassage&urn=urn:cts:greekLit:tlg0544.tlg001.opp-grc1:3.17>: instead of `ὁποῖα οὔκ έστιν` (έστιν with acute, without breathing) the text should read `ὁποῖα οὔκ ἐστιν` (ἐστιν with breathing, without accent); cf. p. 138 of the source at <https://archive.org/details/rsoperarecensuit01sextuoft/page/138>.

**Comment by lcerrato** [comment]
@nevenjovanovic 
Thank you!
