### ISSUE TITLE
tlg2768.tlg002.opp-grc1

### ISSUE THREAD

**Issue by annettegessner** [OpenGreekAndLatin/First1KGreek#215]
Greek text of Gelasius with Latin translation under the footnotes.
Latin text sometimes in a paragraph, sometimes in a footnote. Div-tags for Latin text have to be added.
Since this work has only 9 physical pages, the file can be corrected manually. Otherwise it's problems are similar to the files mentioned in #211 .

**Comment by annettegessner** [comment]
I split the files manually to see, if there were any other problems regarding this issue, but there weren't. The only thing that had to be looked up closely was the chapters for the Latin textparts, the rest could maybe even have been automatized.

**Comment by annettegessner** [comment]
@sonofmun: Is there a "cool" way to find files including Latin translations? I found this by searching for files including the (randomly chosen) Latin word "quam" and it didn't have an issue assigned for it yet.

**Comment by sonofmun** [comment]
I would think that looking for a common word would be the best way to go about it. Though these will also often appear in the Latin titles of Greek works, so it will also produce some noise.
