### ISSUE TITLE
(tlg0607) tlg0607.tlg001.1st1K.grc1-Test file from DDD

### ISSUE THREAD

**Issue by AlisonBabeu** [OpenGreekAndLatin/First1KGreek#2162]
Loaded the text of Aelius Theon from the DDD repository.
Currently looking at corrections needed to CTSize the file.
Turns out half of the work (pg. 106-130) are also missing.

**Comment by lcerrato** [comment]
see https://travis-ci.org/OpenGreekAndLatin/First1KGreek/builds/602911652

**Comment by lcerrato** [comment]
Some initial comments:
funder is empty `<funder></funder>`

needs a ref target to https://archive.org/details/rhetoresgraeci00spengoog/page/n90

`<change>Alison Babeu-added file into First1K repository, added in a CTS refsDecl</change>`
should follow the format
`<change who="Alison Babeu" when="2019-10-25">added file into First1K repository, added in a CTS refsDecl</change>`

`<text>` needs to declare a language `<text xml:lang="grc">`

move the top level head to just under the type="edition" tag

`<note type="marginal"> should be <milestone type="page" resp="Walz" n="#"/>`
use the regex `<note type="marginal">(\d+)</note>` change to `<milestone unit="page" resp="Walz" n="$1"/>`

strike the digits that appear following the chapter changes (just after the `<p>` tags)

cosmetic: indicate where the paragraphs indent on the page and where quotes appear
so `<p>` would become `<p rend="indent">`
be careful — a quote is not an indented paragraph
so here `<lg>` can become `<quote>` and `</lg>` should be `</quote>`

**Comment by lcerrato** [comment]
CTS changes (basic OGL level)

in the `<encodingDesc>` include something like `  <editorialDecl><p>This appears to be a partial work and includes only chapters 1-6</p></editorialDecl>`

strike the book level tags so `<div type="textpart" subtype="book" n="1">` and one of the closing `</div>`
change the refsDecl accordingly:

`<refsDecl n="CTS">`
        `<cRefPattern n="chapter" matchPattern="(.+)" replacementPattern="#xpath(/tei:TEI/tei:text/tei:body/tei:div/tei:div[@n='$1'])">`
            `<p>This pointer pattern extracts chapter</p>`
        `</cRefPattern>`
   ` </refsDecl>`
` <!--<refsDecl n="CTS">`
  `<cRefPattern n="chapter" matchPattern="(.+).(.+)" replacementPattern="#xpath(/tei:TEI/tei:text/tei:body/tei:div/tei:div[@n='$1']/tei:div[@n='$2'])"/>`
  `<cRefPattern n="book" matchPattern="(.+)" replacementPattern="#xpath(/tei:TEI/tei:text/tei:body/tei:div/tei:div[@n='$1'])"/>`
` </refsDecl>-->`

**Comment by lcerrato** [comment]
We can talk about an enhanced CTS markup approach once we have the basic one passing. :)

**Comment by lcerrato** [comment]
On the titles/labels, I would use the more common name in the file (if not in the workgroup) since we want what appears in SV to be concise.

so Aelius Theon might be preferable to the one with the date and this should be the `<author>` in the text file.

Also, I have been using the Greek title in the xml file = cts label. so Προγυμνάσματα

**Comment by AlisonBabeu** [comment]
Thanks for all the helpful comments, something to get started on next week!

**Comment by lcerrato** [comment]
fixed per #2164
