### ISSUE TITLE
(tlg0607.tlg001.1st1K.grc1) many words had a character cut off in the page margin

### ISSUE THREAD

**Issue by AlisonBabeu** [OpenGreekAndLatin/First1KGreek#2163]
There are various locations in this file where there are incorrect words/typos, it seems to have occurred with words that were in the page margin, and the first character of the word was cut off.  

For example, page 83, line 14-15 (https://babel.hathitrust.org/cgi/pt?id=mdp.39015013123289&view=2up&seq=114) should read:

"Ὁμοίως δὲ ἔσται καὶ σύντομος ἡ διήγησις ἐκ τῶν πραγμάτων καὶ τῆς λέξεως"

but in our XML file we have 

"Ὁμοίως δὲ ἔσται καὶ σύντομος ἡ διήγησις ἐκ τῶν **ραγμάτων** καὶ τῆς λέξεως." 

The π was in the page margin and was cut off. This seems to have happened unfortunately in many places. I fixed a few of the first ones I found but this is clearly a more systematic issue.

**Comment by lcerrato** [comment]
ran a spellcheck on this

**Comment by lcerrato** [comment]
fixed per #2167
