### ISSUE TITLE
data/tlg4102/tlgX01/tlg4102.tlgX01.opp-grc1.xml : Add title of the text

### ISSUE THREAD

**Issue by PonteIneptique** [OpenGreekAndLatin/First1KGreek#217]
Currently, [tlg4102.tlgX01.opp-grc1.xml](https://github.com/OpenGreekAndLatin/First1KGreek/blob/master/data/tlg4102/tlgX01/tlg4102.tlgX01.opp-grc1.xml) has not the title of the text in it. I do not know how widespread this issue is but the title of the text (And not of the book it is in) should be accessible from the TEI file itself

**Comment by annettegessner** [comment]
This seems to be the same issue I already addressed in Patrologia Latina [issue 107](https://github.com/OpenGreekAndLatin/patrologia_latina-dev/issues/107).

Could you direct me to a file, which has the "perfect header" to use as a pattern for other files? I fear we might have very varying degrees of information being there, not being there, being there two times or at the wrong place. 
If I understand correctly, the information about the work (ancient author, work title) should be in `<titleStmt>`. On the other the title of the book it was scanned from goes into `<sourceDesc>`. But for instance information about the ´<editor>´ is often in both of those tags. So I'd like to make sure, we all have a proper file to look at if we are in doubt about how the `<fileDesc>`should ideally look like.

**Comment by PonteIneptique** [comment]
https://github.com/PerseusDL/canonical-latinLit/blob/master/data/phi1294/phi002/phi1294.phi002.perseus-lat2.xml

**Comment by annettegessner** [comment]
since this concerns ALL files, I just opened a new issue #227, 
closing this one
