### ISSUE TITLE
Add new text

### ISSUE THREAD

**Issue by karpalig** [OpenGreekAndLatin/First1KGreek#2176]
Please help me to find first step "How to add new text"

**Comment by lcerrato** [comment]
Hi @karpalig!
We have many files in process or on the working list — let me know what you are interested in and I can see where we are with those works.

We do not have any centralized documentation on adding texts at this time but we are hoping to set up a workflow for publication in the near future. Ideally, we'd like to point to other repos to keep text management decentralized, so that the Scaife Viewer can publish the works.

We are also looking to add annotation tools to the online environment to make it easier to publish translations and text alignments — not all contributions will be need to be xml files.

**Comment by karpalig** [comment]
If possible, for example, I can install a reader locally, I will copy this database. how can I edit text or add a new one. I was looking for manuals or hot-tos, but too much technical information. Maybe there is still no visual text editor that can connect to the database and publish the text? Oxygen doesn't help me either. 

I really want to learn , please help me figure out how to publish mine text. I want to teach my students and publish Russian translations

Thank you for your time I really appreciate the support!

**Comment by lcerrato** [comment]
We have partners working on all phases of work from scanning and [multi-lingual OCR](http://heml.mta.ca/lace/index.html), TEI-XML editing, and [Scaife Viewer](https://scaife-viewer.org) development, so there are different sets of tools and recommendations for best practices but not all collaborators work in the same area of focus.

I am hoping to address your question as best I can in this format. In brief, I can summarize a little here, but this will not be a complete picture of the entire OGL ecosystem. My brevity may also not do justice to all of the partners. 

All that is required to publish in the Scaife Viewer (or any CTS-based viewer) is basic canonical text services (CTS) compliance and 2) accessibility. 

(Note: We do produce [EpiDoc compliant](http://www.stoa.org/epidoc/gl/latest/) TEI-XML, but while this is the standard for our current texts, it is not a requirement for the reader itself.) 

CTS requires 1) a text file with a specific structure (edition, translation, or commentary), and 2) metadata files. These need to be stored and presented in a nested format. 

The [Scaife Viewer](https://scaife.perseus.org) is then pointed to these CTS-complaint repositories (it draws from 9 of these at present). OGL uses GitHub for storage and accessibility of those files, but this is just current practice. 

Contributors use a variety of tools to create texts. There is no suite of prepackaged tools we offer that plugs directly into the reader. We envision this to be a flexible and extensible publishing environment. (Oxygen is indeed what we use at Perseus for editing, but some of the small edits are done directly on GitHub and others have their own preferred tools.)

Ideally, we see a range of contributions. Some users will provide translations, treebanks, alignments and annotations within the Viewer itself or via associated/linked tools. Others may wish to offer fully marked up XML texts. These could be hosted in repositories they manage themselves that we point the Viewer (which is preferable for expanding collections) to or we could place them in our hosted collections (such as for a single work).

This is just a very succinct overview but right now the workflow is fairly decentralized as we see contributors adding a wide variety of materials in different states of completion.

**Comment by karpalig** [comment]
Thank you very much for your time, you really clarified many questions. I wish you good health!
