### ISSUE TITLE
Fixes to https://opengreekandlatin.github.io/First1KGreek/

### ISSUE THREAD

**Issue by lcerrato** [OpenGreekAndLatin/First1KGreek#2181]
@ThomasK81 
So I ran the TEItoCEX and produced a json file, but it looks like there are other transformations needed to update the https://opengreekandlatin.github.io/First1KGreek/ page?

**Comment by lcerrato** [comment]
Also need a link to https://www.opengreekandlatin.org

**Comment by ThomasK81** [comment]
Sorry I forgot to push some changes to TEItoCEX! My bad! :(

1. run TEItoCEX in the data folder of First1K master: `./TEItoCEX catalog.json -Cat`
2. Copy the resulting `catalog.json` into the `\build` folder of the `gh-pages` branch
3. Commit and push the changes of the `gh-pages` branch
4. Enjoy the updated website. :D
