### ISSUE TITLE
new texts: those in physicietmedicig01ideluoft 

### ISSUE THREAD

**Issue by brobertson** [OpenGreekAndLatin/First1KGreek#2183]
[physicietmedicig01ideluoft_done.zip](https://github.com/OpenGreekAndLatin/First1KGreek/files/4600646/physicietmedicig01ideluoft_done.zip)

**Comment by brobertson** [comment]
Lisa, can you put a proofreader responsibility statement on these for 'McIntire, Madeline'? She did everything but zoning and urns.

**Comment by lcerrato** [comment]
@brobertson 
Let's keep this notation here.
(At this stage, I'm not assuming I will be the person handling all of these files.)

**Comment by lcerrato** [comment]
Since this is 2 files, this issue needs splitting.

**Comment by lcerrato** [comment]
urn.cts.greekLit.tlg0733.tlg001.1st1K-grc1.xml
urn.cts.greekLit.tlg0732.tlg003.1st1K-grc1.xml

**Comment by lcerrato** [comment]
bumped to #2184 and #2185
