### ISSUE TITLE
(tlg0026.tlg004.1st1k-grc1.xml) new edition

### ISSUE THREAD

**Issue by rebeccadraughon** [OpenGreekAndLatin/First1KGreek#2188]
[urn.cts.greekLit.tlg0026.tlg004.1st1K-grc1.xml.zip](https://github.com/OpenGreekAndLatin/First1KGreek/files/4616242/urn.cts.greekLit.tlg0026.tlg004.1st1K-grc1.xml.zip)

**Comment by lcerrato** [comment]
- [ ] fix header

- [ ] add refsDecl

- [ ] fix body tags

- [ ] create metadata files

- [ ] check catalog and CITE tables

- [ ] Update pick list and Trello card when complete

**Comment by lcerrato** [comment]
I bumped the existing file as found in the catalog: https://catalog.perseus.org/catalog/urn:cts:greekLit:tlg0026.tlg004.opp-grc2
