### ISSUE TITLE
corpusculumpoesi01lipsuoft new editions

### ISSUE THREAD

**Issue by brobertson** [OpenGreekAndLatin/First1KGreek#2199]
[corpusculumpoesi01lipsuoft.zip](https://github.com/OpenGreekAndLatin/First1KGreek/files/4740975/corpusculumpoesi01lipsuoft.zip)

Comprises: 
  urn.cts.greekLit.tlg1486.tlg001.1st1K-grc1  
  urn.cts.greekLit.tlg1801.tlg001.1st1K-grc1  
  urn.cts.greekLit.tlg1486.tlg002.1st1K-grc1  
  urn.cts.greekLit.tlg0233.tlg001.1st1K-grc1

**Comment by lcerrato** [comment]
see #2201 #2202 #2203 #2204
