### ISSUE TITLE
update catalog.json

### ISSUE THREAD

**Issue by lcerrato** [OpenGreekAndLatin/First1KGreek#2207]
@ThomasK81 

So I have TEItoCEX in my First1kGreek folder on master (note it's not in the repo here, though).
I run `./TEItoCEX catalog.json -Cat`
and it seems to work and exit ok, but I do not see any changes to the catalog.json file

What I see locally is an old catalog.json file in the top level directory (no changes made). 

It seems like I didn't actually create the new catalog.json

What step am I missing?

**Comment by ThomasK81** [comment]
Sorry, Lisa, that was my bad. I forgot to push the latest version to TEItoCEX. BTW, I had put `TEItoCEX` into the `.gitignore`, so we are more flexible. Ideally you place and run it in the `data` folder. Once `catalog.json` is created you move that to the root and you should be good to commit. Sorry for the confusion!

**Comment by lcerrato** [comment]
@ThomasK81 
Thanks! I realized it doesn't much matter since things aren't pushed out to SV yet but I started a wiki page so that I could test this and do this in the future. :)

**Comment by ThomasK81** [comment]
BTW, I restructured TEItoCEX now, so that one has to download the latest release to get to the binaries (the advantage that it now produces binaries for all major systems). We will eventually include it in a GitHub Action, so you do not have to do any manual work. :)

**Comment by lcerrato** [comment]
`~/Development/OGL:First1kGreek/data$ ./TEItoCEX catalog.json -Cat`
KKGGGKGGM582020/06/25 15:26:50 Error: EOF
panic: EOF

goroutine 1 [running]:
main.check(0x11d7900, 0xc00008e100)
	/home/runner/work/TEItoCEX/TEItoCEX/CTSExtract.go:1871 +0xd1
main.main()
	/home/runner/work/TEItoCEX/TEItoCEX/CTSExtract.go:804 +0x15513

**Comment by ThomasK81** [comment]
I should have tested the new version!! :( I was too vicious in my error handling. I fixed it: https://github.com/ThomasK81/TEItoCEX/releases/tag/v1.0.10 
Please try again.

**Comment by lcerrato** [comment]
success!

**Comment by lcerrato** [comment]
@ThomasK81 
I notice that the new items include the second title line, which in these new files is `<title type="sub">an electronic transcription.</title>`

Either I can remove this, as it is not in the older files, or we might want to ignore a second `<title>`

**Comment by lcerrato** [comment]
I should add I've already spotted other inconsistencies via this file — it.is.awesome!!!

**Comment by ThomasK81** [comment]
Re: title, whichever you want. I’m not sure whether the xml file really needs the sub-title though. :)

**Comment by lcerrato** [comment]
@ThomasK81 I've been editing it from Perseus (inconsistently). Seems superfluous.

**Comment by lcerrato** [comment]
Solved and documented in the wiki!
