### ISSUE TITLE
(tlg0093.tlg010.1st1K-grc1.xml -> tlg0093.tlg010x09.1st1K-grc1.xml) new edition

### ISSUE THREAD

**Issue by beccafrank** [OpenGreekAndLatin/First1KGreek#2215]
The first file contains all the text except for urn:cts:greekLit:tlg0093.tlg010.1st1K-grc1:90 to urn:cts:greekLit:tlg0093.tlg010.1st1K-grc1:96, which are in the second file.

[urn.cts.greekLit.tlg0093.tlg010.1st1K-grc1.xml.zip](https://github.com/OpenGreekAndLatin/First1KGreek/files/4875682/urn.cts.greekLit.tlg0093.tlg010.1st1K-grc1.xml.zip)

[urn.cts.greekLit.tlg0093.tlg010.1st1K-grc1.xml.zip](https://github.com/OpenGreekAndLatin/First1KGreek/files/4875681/urn.cts.greekLit.tlg0093.tlg010.1st1K-grc1.xml.zip)

- [x] special issues: restitch file and rename file

- [x] fix header

- [x] add refsDecl

- [x] fix body tags

- [x] create metadata files

- [x] check catalog and CITE tables

- [x] hyphenation and specialized tags; languages

- [x] Update pick list and Trello card when complete

**Comment by mkonieczny9805** [comment]
So I actually tried to work on these files to combine them into one, but the computer I'm using can't handle the first, larger one. I wonder if that's because it's output as a singe gigantic line of text?

**Comment by mkonieczny9805** [comment]
@lcerrato @beccafrank So I did finally get this file working, and recombined the two files above into one. Something I noticed, however, is that most of the in-text citations have somehow gotten truncated, e.g.:

`(Simpl. in Arist. Categ. </tei:p></tei:div>`

I double checked to make sure this was originally in the file and not something I accidentally introduced with my find and replace (which I did not insert some line breaks). Any idea what the issue is? The text is no longer up on Lace so I can't check there.

**Comment by lcerrato** [comment]
@mkonieczny9805 I cannot see these references in the pdf. Where should I be looking for them? I can't tell which page this work starts on or where to look. I don't see (Simpl. in Arist.) or any references.

It looks like possibly the reference number has been transformed into tags or the ref is the Greek letter and the numbers are breaking this up. But without the scan it's impossible to decipher.
`(Simpl. in Arist. Categ. f. </tei:p></tei:div></tei:div><tei:div type="textpart" subtype="1" n="urn:cts:greekLit:tlg0093.tlg010.1st1K-grc1:16"><tei:div type="textpart" subtype="2" n="urn:cts:greekLit:tlg0093.tlg010.1st1K-grc1:16.1"><tei:p`

**Comment by mkonieczny9805** [comment]
You can see some examples here, from the series of fragments beginning on printed page 417:
https://archive.org/details/bub_gb_6dXhmh761sYC/page/n453/mode/2up

It looks like many of the concluding references have been truncated in the output, as the example above indicates.

**Comment by mkonieczny9805** [comment]
@lcerrato Actually I have a pretty good idea of what might have happened. As you can see in the link, many of the concluding refs. spill over onto a final line that includes just a few characters of text. Most likely these short lines were simply omitted by the OCR.

**Comment by lcerrato** [comment]
This is why I'd like book page numbers — I could not figure out where in the pdf to look for the start of this! I was hunting everywhere.
Yes, end lines were being cut off in this earlier Lace work. 
My question now is how these files are separated and what to call these.  It looks like they were separated into different Fragments and need renaming. How far did you get?

**Comment by lcerrato** [comment]
Ok, I see the breakdown in TLG. These file names are still inaccurate (the 1st1K part is missing from the later batch). I guess I would have not kept this one as an id.
De odoribus (fr. 4): pp. 364-376
De ventis (fr. 5): pp. 376-389
De signis tempestatum (fr. 6): pp. 389-398
De lassitudine (fr. 7): pp. 398-401
De vertigine (fr. 8): pp. 401-403
De sudore (fr. 9): pp. 403-408
De animi defectione (fr. 10): p. 409
De nervorum resolutione (fr. 11): pp. 409-410
Fragmenta varia (frr. 13-190): pp. 417-462

**Comment by mkonieczny9805** [comment]
@lcerrato You have to ask @beccafrank , I didn't do the Lace work on this. Also not sure how zoning page numbers works on Lace: do you have to mark them with CTS URNs like the primary text? @brobertson any suggestions?

**Comment by lcerrato** [comment]
@mkonieczny9805 
The problem is that Lace discards the book page numbers in export. I really would like that to change. It is too easy to get lost. I add them back when I am creating texts (such as Euripides).

**Comment by mkonieczny9805** [comment]
@lcerrato For the short texts I've been working up in Oxygen, I have restored printed page numbers as attributes in the <pb> tags in instances where page numbers are the conventional means of citing a text, e.g. in Rhetores Graeci or Grammatici Graeci.

**Comment by brobertson** [comment]
The thing is, book page numbers never actually exist as reliable data in the process. There are image numbers (which become OCR output page numbers) and there are Lace sequence numbers (which are the image numbers offset as a blown page offers no output).

I"ve been thinking about this, though, and we could add a box above the page image for the editor to add the print page number.
________________________________

**Comment by lcerrato** [comment]
@AlisonBabeu 
I think that they kept this is ID tlg0093.tlg010 for the **Fragmenta varia (frr. 13-190): pp. 417-462** and created new derivative IDs for the named Fragments, but, I would find it confusing to keep this ID. This one implies that all of the fragments are here but they are not. 
I would prefer to mint a new one for this edition (x09) urn.cts.greekLit.tlg0093.tlg010x09.1st1K-grc1 (note that the project part of the urn is missing from others in this batch).
This prevents the expectation that all Fragments are here.

**Comment by mkonieczny9805** [comment]
@brobertson I think that would be really useful!

**Comment by lcerrato** [comment]
@brobertson @mkonieczny9805 
I have to confess they are often misread and garbled (even in Abbyy when the page is perfect and everything is in English), so I hate the idea of any major effort being invested if people are going to be fixing digits all the time.
In this case, I couldn't find the right starting page because of the way the files were split. I usually can figure out the offset between Lace pbs and the pdf but I was really lost!
In general, we have the pdf links in the spreadsheet, so this is an outlier: the spreadsheet has one entry for nine texts and no clear starting point for this file.

**Comment by lcerrato** [comment]
@mkonieczny9805 
I'm going to focus on the metadata for this set of files unless you have something already.

**Comment by brobertson** [comment]
Print page numbers do not reliably have any of the qualities one looks for in an identifier: they are neither sequential nor unique nor universally applied. There are image sets representing volumes without page numbers. There are image sets with duplicate page numbers, i.e. two page 200s. There are image sets where x is before 100 and x is after 100. It might be ok  to use them as identifiers in a given volume, but not across all.

Lace output gives image sequence numbers in <pb> elements. If this were more easily accessed when viewing Lace, it might make things easier for a XML editor.
________________________________

**Comment by mkonieczny9805** [comment]
@lcerrato Go ahead, the only things I've done here have been the recombinations of separated files.

**Comment by mkonieczny9805** [comment]
@brobertson I think the point is not to rely on original page numbers as unique identifiers, but as a way of being able to refer back to the original printed volume when necessary, esp. while editing and in instances where people have been using these numbers as the conventional citation method since original publication.
