### ISSUE TITLE
tlg0693.tlg001.1st1K-grc1.xml Plato et al

### ISSUE THREAD

**Issue by lanielsen1** [OpenGreekAndLatin/First1KGreek#2224]
[platonisdialogi06plat.zip](https://github.com/OpenGreekAndLatin/First1KGreek/files/4880953/platonisdialogi06plat.zip)

- [x] fix header

- [x] add refsDecl

- [x] fix body tags

- [x] create metadata files

- [x] check catalog and CITE tables

- [x] hyphenation and specialized tags; languages

- [x] special issues found on Trello card?

- [x] Update pick list and Trello card when complete

**Comment by lcerrato** [comment]
- [ ] fix header

- [ ] add refsDecl

- [ ] fix body tags

- [ ] create metadata files

- [ ] check catalog and CITE tables

- [ ] hyphenation and specialized tags; languages

- [ ] special issues found on Trello card?

- [ ] Update pick list and Trello card when complete

**Comment by mkonieczny9805** [comment]
@brobertson Can we put this back up on Lace for further proofreading?

**Comment by brobertson** [comment]
Sure!

On Aug. 9, 2020 5:18 p.m., mkonieczny9805 <notifications@github.com> wrote:

@brobertson<https://github.com/brobertson> Can we put this back up on Lace for further proofreading?

**Comment by lcerrato** [comment]
@mkonieczny9805 
Do you have a version of this? I see the boxes checked but I don't see a version attached?

**Comment by mkonieczny9805** [comment]
I started working on the file and saw that there were a lot of proofreading errors, so Bruce is supposed to put it back on Lace for further editing. It’s on hold for the time being.

**Comment by brobertson** [comment]
I've lost the plot: what's the volume id for this URN? It doesn't come up in Trello.
________________________________

**Comment by mkonieczny9805** [comment]
urn:cts:greekLit:tlg0693.tlg002.1st1K-grc1 0693.002 Introductio in Platonem oclc.1982818Platonis dialogi secundum Thrasylli tetralogias dispositi, vol. 6 (1855) 147-151 ῾Albinus, Introduction to Plato's Dialogues῾
urn:cts:greekLit:tlg0693.tlg001.1st1K-grc1 0693.001 Epitome doctrinae Platonicae sive Διδασκαλικός oclc.1982818 Platonis dialogi secundum Thrasylli tetralogias dispositi, vol. 6 (1855) 152-189 "Albinus, Handbook of Platonism"
 
from platonisdialogi06plat
