### ISSUE TITLE
(tlg2016.tlg001.1st1K-grc1) new edition

### ISSUE THREAD

**Issue by jsellick** [OpenGreekAndLatin/First1KGreek#2230]
[urn.cts.greekLit.tlg2016.tlg001.1st1K-grc1.xml.zip](https://github.com/OpenGreekAndLatin/First1KGreek/files/4962570/urn.cts.greekLit.tlg2016.tlg001.1st1K-grc1.xml.zip)

- [x] fix header

- [x] add refsDecl

- [x] fix body tags

- [x] create metadata files

- [x] check catalog and CITE tables

- [x] hyphenation and specialized tags; languages

- [x] special issues found on Trello card?

- [x] Update pick list and Trello card when complete

**Comment by mkonieczny9805** [comment]
[urn.cts.greekLit.tlg2016.tlg001.1st1K-grc1.xml.zip](https://github.com/OpenGreekAndLatin/First1KGreek/files/4962563/urn.cts.greekLit.tlg2016.tlg001.1st1K-grc1.xml.zip)

TEI file of Greek version
