### ISSUE TITLE
(tlg1286.tlg001.1st1K-grc1.xml- tlg1286.tlg020.1st1K-grc1.xml) new edition

### ISSUE THREAD

**Issue by ahanhardt** [OpenGreekAndLatin/First1KGreek#2259]
[urn.cts.greekLit.tlg1286.tlg001.1st1K-grc1.xml.zip](https://github.com/OpenGreekAndLatin/First1KGreek/files/5105246/urn.cts.greekLit.tlg1286.tlg001.1st1K-grc1.xml.zip)
[urn.cts.greekLit.tlg1286.tlg002.1st1K-grc1.xml.zip](https://github.com/OpenGreekAndLatin/First1KGreek/files/5105247/urn.cts.greekLit.tlg1286.tlg002.1st1K-grc1.xml.zip)
[urn.cts.greekLit.tlg1286.tlg003.1st1K-grc1.xml.zip](https://github.com/OpenGreekAndLatin/First1KGreek/files/5105248/urn.cts.greekLit.tlg1286.tlg003.1st1K-grc1.xml.zip)
[urn.cts.greekLit.tlg1286.tlg004.1st1K-grc1.xml.zip](https://github.com/OpenGreekAndLatin/First1KGreek/files/5105249/urn.cts.greekLit.tlg1286.tlg004.1st1K-grc1.xml.zip)
[urn.cts.greekLit.tlg1286.tlg005.1st1K-grc1.xml.zip](https://github.com/OpenGreekAndLatin/First1KGreek/files/5105250/urn.cts.greekLit.tlg1286.tlg005.1st1K-grc1.xml.zip)
[urn.cts.greekLit.tlg1286.tlg006.1st1K-grc1.xml.zip](https://github.com/OpenGreekAndLatin/First1KGreek/files/5105251/urn.cts.greekLit.tlg1286.tlg006.1st1K-grc1.xml.zip)
[urn.cts.greekLit.tlg1286.tlg007.1st1K-grc1.xml.zip](https://github.com/OpenGreekAndLatin/First1KGreek/files/5105252/urn.cts.greekLit.tlg1286.tlg007.1st1K-grc1.xml.zip)
[urn.cts.greekLit.tlg1286.tlg008.1st1K-grc1.xml.zip](https://github.com/OpenGreekAndLatin/First1KGreek/files/5105253/urn.cts.greekLit.tlg1286.tlg008.1st1K-grc1.xml.zip)
[urn.cts.greekLit.tlg1286.tlg009.1st1K-grc1.xml.zip](https://github.com/OpenGreekAndLatin/First1KGreek/files/5105254/urn.cts.greekLit.tlg1286.tlg009.1st1K-grc1.xml.zip)
[urn.cts.greekLit.tlg1286.tlg010.1st1K-grc1.xml.zip](https://github.com/OpenGreekAndLatin/First1KGreek/files/5105255/urn.cts.greekLit.tlg1286.tlg010.1st1K-grc1.xml.zip)
[urn.cts.greekLit.tlg1286.tlg011.1st1K-grc1.xml.zip](https://github.com/OpenGreekAndLatin/First1KGreek/files/5105256/urn.cts.greekLit.tlg1286.tlg011.1st1K-grc1.xml.zip)
[urn.cts.greekLit.tlg1286.tlg012.1st1K-grc1.xml.zip](https://github.com/OpenGreekAndLatin/First1KGreek/files/5105257/urn.cts.greekLit.tlg1286.tlg012.1st1K-grc1.xml.zip)
[urn.cts.greekLit.tlg1286.tlg013.1st1K-grc1.xml.zip](https://github.com/OpenGreekAndLatin/First1KGreek/files/5105258/urn.cts.greekLit.tlg1286.tlg013.1st1K-grc1.xml.zip)
[urn.cts.greekLit.tlg1286.tlg014.1st1K-grc1.xml.zip](https://github.com/OpenGreekAndLatin/First1KGreek/files/5105259/urn.cts.greekLit.tlg1286.tlg014.1st1K-grc1.xml.zip)
[urn.cts.greekLit.tlg1286.tlg016.1st1K-grc1.xml.zip](https://github.com/OpenGreekAndLatin/First1KGreek/files/5105260/urn.cts.greekLit.tlg1286.tlg016.1st1K-grc1.xml.zip)
[urn.cts.greekLit.tlg1286.tlg017.1st1K-grc1.xml.zip](https://github.com/OpenGreekAndLatin/First1KGreek/files/5105261/urn.cts.greekLit.tlg1286.tlg017.1st1K-grc1.xml.zip)
[urn.cts.greekLit.tlg1286.tlg018.1st1K-grc1.xml.zip](https://github.com/OpenGreekAndLatin/First1KGreek/files/5105262/urn.cts.greekLit.tlg1286.tlg018.1st1K-grc1.xml.zip)
[urn.cts.greekLit.tlg1286.tlg019.1st1K-grc1.xml.zip](https://github.com/OpenGreekAndLatin/First1KGreek/files/5105263/urn.cts.greekLit.tlg1286.tlg019.1st1K-grc1.xml.zip)
[urn.cts.greekLit.tlg1286.tlg020.1st1K-grc1.xml.zip](https://github.com/OpenGreekAndLatin/First1KGreek/files/5105264/urn.cts.greekLit.tlg1286.tlg020.1st1K-grc1.xml.zip)

(The edition does not include tlg1286.tlg015.1st1K-grc1.xml)

**Comment by ahanhardt** [comment]
@lcerrato if no one has taken on this group of texts, I would like to reserve them for myself and a former CHS summer intern to work on

**Comment by lcerrato** [comment]
- [ ] fix header

- [ ] add refsDecl

- [ ] fix body tags

- [ ] add first page link as milestone (if not possible to link in header)

- [ ] create metadata files (if needed)

- [ ] check catalog and CITE tables

- [ ] hyphenation and specialized tags such as q, add, del, sic; languages; digits in text

- [ ] make sure there are spaces before/after page break tags and merge split words broken by pb tags

- [ ] check for period at end of section (to avoid missing word drop out)

- [ ] line breaks and special indentation 

- [ ] special issues found on Trello card?

- [ ] Update pick list and Trello card when complete

**Comment by lcerrato** [comment]
@ahanhardt 
No, no one has claimed these. If you'd like me to make an initial cts metadata file, I will do so. The rest will be based on that if these are the same volume.

**Comment by ahanhardt** [comment]
@charhoughton

**Comment by charhoughton** [comment]
@lcerrato do you want us to submit these on separate pull requests or all at once?

**Comment by lcerrato** [comment]
@charhoughton 
We can try all at once.

**Comment by lcerrato** [comment]
tlg1286.tlg020.1st1K-grc.xml
there is a page missing from the scan print page 388:
https://archive.org/details/ScottHermeticaVolOne/page/n391/mode/2up
