### ISSUE TITLE
tlg0086.tlg015 and tlg0086.tlg021 are reversed?

### ISSUE THREAD

**Issue by AlisonBabeu** [OpenGreekAndLatin/First1KGreek#2266]
I have been working my way back through the First1K texts in order to create catalog data and noticed that two texts for Aristotle have the incorrect identifiers. 

tlg0085.tlg015 (https://github.com/OpenGreekAndLatin/First1KGreek/blob/master/data/tlg0086/tlg015/tlg0086.tlg015.1st1K-grc1.xml is listed as De animalium motione, but the correct work for this ID is De incessu animalium.  I checked the text of the file in GitHub against the TLG edition (and the Perseus Catalog record) and unless I am mistaken it appears that this is actually the text of work tlg0086.tlg021  (De motu animalium).   

I then checked the GitHub file for the work tlg0086.tlg021 (https://github.com/OpenGreekAndLatin/First1KGreek/blob/master/data/tlg0086/tlg021/tlg0086.tlg021.1st1K-grc1.xml), which has been labelled as De animalium incessu, although the correct work for this ID is De animalium motione.  The text in this GitHub file also appears to be the text of work tlg0086.tlg015, De incessu animalium.

Could someone double check these two works to make sure that I"m not mistaken and if I'm not, I will move the texts and update the CTS and title information.  Thanks!

**Comment by lcerrato** [comment]
@AlisonBabeu 
These appear to be reversed.

De incessu animalium. {0086.015} 
(704a) ΠΕΡΙ ΠΟΡΕΙΑΣ ΖΩΙΩΝ    
  Περὶ δὲ τῶν χρησίμων μορίων τοῖς ζῴοις πρὸς τὴν κίνησιν τὴν κατὰ τόπον ἐπισκεπτέον διὰ τίνα αἰτίαν τοιοῦτόν ἐστιν

De motu animalium. {0086.021}
(698a) ΠΕΡΙ ΖΩΙΩΝ ΚΙΝΗΣΕΩΣ   
  Περὶ δὲ κινήσεως τῆς τῶν ζῴων, ὅσα μὲν αὐτῶν περὶ ἕκαστον ὑπάρχει γένος, καὶ τίνες διαφοραί, καὶ τίνες αἰτίαι

**Comment by lcerrato** [comment]
I have changed the files and associated data to reflect this correction.
