### ISSUE TITLE
uc1.32106001545281-1592502209 (Lucretius)

### ISSUE THREAD

**Issue by spearpearl** [OpenGreekAndLatin/First1KGreek#2316]
[uc1.32106001545281-1592502209.zip](https://github.com/OpenGreekAndLatin/First1KGreek/files/6038165/uc1.32106001545281-1592502209.zip)

**Comment by lcerrato** [comment]
@spearpearl  Thanks!
Hi Pearl, This is Latin and needs to go in that repo.
https://github.com/OpenGreekAndLatin/Latin/issues

**Comment by lcerrato** [comment]
See https://github.com/OpenGreekAndLatin/Latin/issues/18
