### ISSUE TITLE
(tlg0074.tlg008.1st1K-grc1.xml) new edition

### ISSUE THREAD

**Issue by kcooper42** [OpenGreekAndLatin/First1KGreek#2320]
[ldpd_10922736_000.zip](https://github.com/OpenGreekAndLatin/First1KGreek/files/6095897/ldpd_10922736_000.zip)
File includes 4 separate CTS URNs:
urn:cts:greekLit:tlg0557.tlg004.1st1K-grc1
urn:cts:greekLit:tlg0557.tlg005.1st1K-grc1
urn:cts:greekLit:tlg0575.tlg001.1st1K-grc1
urn:cts:greekLit:tlg0575.tlg002.1st1K-grc1
For more information see the [Trello Card comments](https://trello.com/c/3KzjPHAO/172-edit-ldpd10922736-20ish-pp)

**Comment by lcerrato** [comment]
@kcooper42 
These appear to be really short texts, but in the future, one issue per file is always the best approach. We make exceptions for very short things, but it's really helpful to break things out.
(You can always just attach the download file to the first issue in the batch and cross link from there, so there aren't four or five identical attachments.)

Note that  if you wanted to keep all files here, that should be indicated in the name of the issue.
So, `(tlg0557.tlg001.1st1K-grc1.xml; 002; 004; 005; 008) new editions` would be a better title for a group of files. 

(I also see another file here — 008 — which is not in your list above.

`(tlg0557.tlg004.1st1K-grc1.xml) new edition` gives no indication there are multiple files here

**Comment by lcerrato** [comment]
Actually, I see there are completely different file names involved. So, that makes it hard to properly and succinctly name the issue.
I would not make a practice of batching together files with different author groups. It means we won't be able to find the issues by name.
