### ISSUE TITLE
(urn:cts:greekLit:tlg0086.tlg012.1st1K-grc1.xml) new edition

### ISSUE THREAD

**Issue by hardybritt** [OpenGreekAndLatin/First1KGreek#2334]
[njp.32101073028480-1607542444.zip](https://github.com/OpenGreekAndLatin/First1KGreek/files/6253116/njp.32101073028480-1607542444.zip)

**Comment by hardybritt** [comment]
Volunteer editors:
Campbell Rosener
Tracy Cook
Eric Blum
Amy Vandervelde
Gwyneth Fletcher 
Jasmine Bao
Drake Parker
Nick Bultman
Bob Darrah
Jen Knickerbocker
Gregory Miller
Anne Lee

**Comment by lcerrato** [comment]
@hardybritt 
Does the above order matter or is alphabetical order preferable?

**Comment by hardybritt** [comment]
@lcerrato Alphabetical order works! That was just the order listed on the spreadsheet.

**Comment by charhoughton** [comment]
@lcerrato a volunteer name needs to be changed from Jen Knickerbocker to Milo Knickerbocker. Should I create a new issue for that and one other file with the same change?

**Comment by lcerrato** [comment]
Hi @charhoughton 
You may be able to make the change directly in GitHub (depending on the file size).
