### ISSUE TITLE
tlg0358-Nichomachus of Gerasa-should be Nicomachus of Gerasa?

### ISSUE THREAD

**Issue by AlisonBabeu** [OpenGreekAndLatin/First1KGreek#2372]
tlg0358 has Nichomachus of Gerasa as the main name in the cts file and throughout the metadata for the various wori.

The TLG uses Nicomachus of Gerasa and the VIAF record for this author (https://viaf.org/viaf/316786767/)  shows that Nichomachus is only used in one authority record instance.  I'm pretty sure that Nichomachus Gerasenus that appears in a few places is entirely incorrect.

I propose to change the main CTS textgroup name to Nicomachus of Gerasa and updated the files accordingly to remove any uses of "Nichomachus".  Does this seems acceptable @lcerrato

**Comment by lcerrato** [comment]
@AlisonBabeu 
Sound good to me!

**Comment by AlisonBabeu** [comment]
The pull request for this issue has been approved and merged so I"m closing this issue.
