### ISSUE TITLE
urn:cts:greekLit:tlg0057.tlg037.1st1K-grc1 [New Edition]

### ISSUE THREAD

**Issue by jdeen33** [OpenGreekAndLatin/First1KGreek#2392]
[urn.cts.greekLit.tlg0057.tlg037.1st1K-grc1.zip](https://github.com/OpenGreekAndLatin/First1KGreek/files/6543022/urn.cts.greekLit.tlg0057.tlg037.1st1K-grc1.zip)

Editing Trello Card: [https://trello.com/c/yJzga1Ji](url)
Publishing Trello Card: https://trello.com/c/ijiay913

**Comment by charhoughton** [comment]
@lcerrato claiming for initial markup

**Comment by charhoughton** [comment]
@lcerrato claiming

**Comment by lcerrato** [comment]
@charhoughton see my comments in the pull request.
We may need the Kuhn pages restored (or added).
