### ISSUE TITLE
(stoa0367.stoa001.ogl-lat1) new edition

### ISSUE THREAD

**Issue by hls2mn** [OpenGreekAndLatin/First1KGreek#2428]
[4013894.zip](https://github.com/OpenGreekAndLatin/First1KGreek/files/6744921/4013894.zip)

**Comment by lcerrato** [comment]
67,569 words

**Comment by lcerrato** [comment]
Note this is a Latin text so it will go into https://github.com/OpenGreekAndLatin/Latin
