### ISSUE TITLE
(urn.cts.greekLit.tlg5023.tlg001.1st1K-grc1) new work

### ISSUE THREAD

**Issue by brobertson** [OpenGreekAndLatin/First1KGreek#2434]
[urn.cts.greekLit.tlg5023.tlg001.1st1K-grc1.xml.zip](https://github.com/OpenGreekAndLatin/First1KGreek/files/6802728/urn.cts.greekLit.tlg5023.tlg001.1st1K-grc1.xml.zip)

**Comment by lcerrato** [comment]
169,279 |  18;4812;7352
