### ISSUE TITLE
(tlg0645)_cts.xml and header work

### ISSUE THREAD

**Issue by AlisonBabeu** [OpenGreekAndLatin/First1KGreek#2444]
Completing work on headers and cts files of Justinus Martyr while creating catalog records.

This has led to the "discovery" that [urn:cts:greekLit:tlg0645.tlg002.opp-grc1](https://github.com/OpenGreekAndLatin/First1KGreek/blob/master/data/tlg0645/tlg002/tlg0645.tlg002.opp-grc1.xml)  and [urn:cts:greekLit:tlg0645.tlg002.perseus-grc2 ](https://github.com/OpenGreekAndLatin/First1KGreek/blob/master/data/tlg0645/tlg002/tlg0645.tlg002.perseus-grc2.xml) are duplicate editions.  I'm assuming the perseus-grc2 is the more updated and CTS compliant file but they do both display in the Scaife Viewer.  @lcerrato do you think we should delete one of these XML files since they are both the same edition? 

I also have no idea why the Dialogue with Tryphon is perseus-grc2, since there only seems to have ever been one edition of this work in First1K and Perseus never had an edition.

**Comment by lcerrato** [comment]
The perseus-grc2 edition has no history of work at Perseus.
The editions are identical except one has an incorrect CTS designation of "book" (despite there being chapters noted throughout) and the perseus edition has an extensive header credit section.
opp-grc1 has a better author/title/bibliographic info, however
There is also a minor difference in how page breaks are tagged. 

So there is probably some merging to be done to preserve the credits and info in both files.

**Comment by AlisonBabeu** [comment]
This issue has been resolved so I'm closing it.
