### ISSUE TITLE
Report an issue: urn:cts:greekLit:tlg1193.tlg001.1st1K-grc1:333-337

### ISSUE THREAD

**Issue by ahanhardt** [OpenGreekAndLatin/First1KGreek#2520]
[tlg1193.tlg001.1st1K-grc1.xml](https://github.com/OpenGreekAndLatin/First1KGreek/tree/cdacf1f/data/tlg1193/tlg001/tlg1193.tlg001.1st1K-grc1.xml)

Pria has alerted me that she misspelled one of her volunteer's names, so every time she is mentioned in the attributions it is spelled wrong... Rather than Sana Igbal Ansari, it should be Sana I_q_bal Ansari. 

Her name can also be found in these texts' attributions:
urn:cts:greekLit:tlg0081.tlg013.1st1K-grc1:1-5
urn:cts:greekLit:tlg0081.tlg014.1st1K-grc1:26.1.1
urn:cts:greekLit:tlg0081.tlg016.1st1K-grc1:1.1
urn:cts:greekLit:tlg1269.tlg002.1st1K-grc1:463-467

**Comment by lcerrato** [comment]
@ahanhardt I just committed a change for the files listed above. (Per find and replace)
