### ISSUE TITLE
Incomplete CTS file in tlg1205/tlg001

### ISSUE THREAD

**Issue by jduff-chs** [OpenGreekAndLatin/First1KGreek#255]
ti:label and ti:description for grc2 are left as ???

```xml
<ti:edition urn="urn:cts:greekLit:tlg1205.tlg001.perseus-grc2" workUrn="urn:cts:greekLit:tlg1205.tlg001">
    <ti:label xml:lang="eng">???</ti:label>
    <ti:description xml:lang="eng">???</ti:description>
  </ti:edition>
```

What information should be there instead?

Compare grc1, a different edition of the same text:
```xml
<ti:edition urn="urn:cts:greekLit:tlg1205.tlg001.perseus-grc1" workUrn="urn:cts:greekLit:tlg1205.tlg001">
    <ti:label xml:lang="eng">Supplicatio Pro Christianis</ti:label>
    <ti:description xml:lang="eng">Athenagorae Atheniensis Philosophi Christiani, Supplicatio Pro Christianis</ti:description>
  </ti:edition>
```

**Comment by jduff-chs** [comment]
The same gaps are present in the CTS for tlg1205/tlg002/grc2, these should all be resolved together.

**Comment by jduff-chs** [comment]
The text in question:
https://archive.org/stream/athenagoras00owengoog#page/n17/mode/2up

**Comment by sonofmun** [comment]
If you have found the precise edition, use the title they have for the work in the `<ti:title>` tag and then the author name that they use and this same title, separated by a comma, in the `<ti:description>` tag. If you can't find one of these pieces of information in the edition or in the XML, you can simply use the information from the other edition to fill in this one.
One other thing to notice, in the `__cts__.xml` for grc1 (and in grc2), notice that the xml:lang attribute for the title and the author are "eng". This is obviously not correct as they should be "lat". If you could change those and add them to your pull request, that would be great.

**Comment by jduff-chs** [comment]
Ok, working on this now. It turns out both editions here use the same title and author - is it possible to add "ed. Otto" or similar to differentiate between the two editions?

**Comment by sonofmun** [comment]
As a quick fix, I don't see any problem with adding this in the text of the `<ti:description>` tag.

**Comment by jduff-chs** [comment]
Ok, I'll put it in there, and add it to the pull request, thanks!
