### ISSUE TITLE
Fix /tlg2042/tlg030/tlg2042.tlg030.opp-grc1.xml TRANSLATION

### ISSUE THREAD

**Issue by sonofmun** [OpenGreekAndLatin/First1KGreek#26]
Duplicate references found : 12.10, 12.17, 12.26, 12.12, 12.24, 12.34, 12.35, 12.19, 12.41, 12.38, 12.11, 12.25, 12.23, 12.39, 12.43, 12.30, 12.9, 12.29, 12.15, 12.18, 12.21, 12.40, 12.32, 12.13, 12.27, 12.14, 12.28, 12.20, 12.16, 12.42, 12.31, 12.37, 12.22, 13.30, 13.23, 13.29, 13.13, 13.18, 13.10, 13.20, 13.24, 13.27, 13.25, 13.22, 13.4, 13.17, 13.15, 13.1, 13.11, 13.31, 13.3, 13.8, 13.7, 13.14, 13.26, 13.19, 13.5, 13.2, 13.9, 13.16, 13.21, 13.28, 13.6, 14.3, 14.25, 14.1, 14.4, 14.10, 14.13, 14.15, 14.16, 14.7, 14.18, 14.8, 14.12, 14.24, 14.9, 14.11, 14.5, 14.2, 14.17, 15.9, 15.21, 15.7, 15.11, 15.27, 15.33, 15.26, 15.5, 15.2, 15.37, 15.32, 15.8, 15.16, 15.22, 15.30, 15.29, 15.25, 15.13, 15.23, 15.6, 15.31, 15.36, 15.15, 15.4, 15.34, 15.20, 15.12, 15.1, 15.35, 15.10, 15.17, 15.14, 15.24, 15.18, 15.19, 16.14, 16.17, 16.23, 16.13, 16.6, 16.1, 16.18, 16.7, 16.5, 16.20, 16.19, 16.2, 16.25, 16.29, 16.3, 16.9, 16.22, 16.8, 16.24, 16.11, 16.21, 16.27, 16.16, 16.26, 16.12, 16.28, 16.4, 16.10, 16.15, 17.3, 17.27, 17.29, 17.7, 17.20, 17.12, 17.32, 17.11, 17.19, 17.18, 17.5, 17.1, 17.21, 17.33, 17.31, 17.15, 17.2, 17.17, 17.24, 17.8, 17.13, 17.14, 17.28, 17.34, 17.6, 17.22, 17.9, 17.36, 17.16, 17.4, 17.25, 17.35, 17.10

**Comment by planatheisa** [comment]
I tried finding the scan to this but no luck. There is no reference address given, also the number of the volume is also missing. Not sure what to do with it now. The problem probably is that the Latin translation of some chapters are in the same div as the Greek text, both numbered the same. Also it's rather confusing, there seems to be Greek text in Latin chapters and vice versa.

**Comment by annettegessner** [comment]
Found a link to a scan ad De Gruyter Open:

http://www.degruyter.com/view/books/9783110275452/9783110275452-005/9783110275452-005.xml

or more precisely

http://www.degruyter.com/dg/viewbookchapter.fullcontentlink:pdfeventlink/$002fbooks$002f9783110275452$002f9783110275452-005$002f9783110275452-005.pdf/9783110275452-005.pdf?t:ac=books$002f9783110275452$002f9783110275452-005$002f9783110275452-005.xml

Strangely, in the beginning it's all Greek and at chapter 9 the text starts to split up into Latin and Greek textparts. In theory the Latin textparts (translation should all be marked with `xml:lang="lat"`, in practice many chapters have to be split into the Greek and Latin textparts. How shall we handle this? It doesn't seem like we can make two separate files one containing the Greek and one the Latin text.

**Comment by sonofmun** [comment]
That is exactly what we need to do, i.e., split the Latin out from the Greek and put it in another file.  This should have the URN tlg2042.tlg030.opp-lat1 (or whatever).

**Comment by annettegessner** [comment]
I see! There are some Latin chapters missing, thus my confusion. 
I'll create a second file called tlg2042.tlg030.opp-lat1 and copy all the text inside. Then I am ging to delete the Latin paragraphs in opp-grc1 and the Greek ones in opp-lat1 and that should do.

**Comment by annettegessner** [comment]
Fun facts: 
After a while, e.g. in book 13, chapter 4, the XML doesn't even wrap the Greek and Latin in separate p-tags, so we can't even trust them anymore. AND for the Latin text it will be even harder to determine what is what, since the DIV-tags of chapters seem to work for Greek, but not always for Latin. ALSO on some pages, single lines (I guess at the beginning or end of a physical page) are missing. 
Oh joy, this will take a while! Any thoughts?

All in all, the scan and XML is not the best and I am glad, I have had better experiences with our DDD-scans o far.

**Comment by annettegessner** [comment]
Took me all afternoon to just fix two books of the Greek file. At this point I don't know, if the file is worth all the time spend trying to fix it and I haven't even tried to figure out, when some of the footnotes should only be in the Greek or in the Latin file, but left them all in. 
Should one or more texts appears, which have similar severe problems, I strongly suggest thinking about a new approach or even redoing the XML.

**Comment by annettegessner** [comment]
We'll look and if we find similar files, we will think about sending them (back) to DDD to deal with the XML.
