### ISSUE TITLE
Report an issue: urn:cts:greekLit:tlg0086.tlg001.1st1K-grc2:1.1.1-1.1.5

### ISSUE THREAD

**Issue by bazzakoni** [OpenGreekAndLatin/First1KGreek#2670]
[tlg0086.tlg001.1st1K-grc2.xml](https://github.com/OpenGreekAndLatin/First1KGreek/tree/5516db3/data/tlg0086/tlg001/tlg0086.tlg001.1st1K-grc2.xml)

Wrong text and letter missing. Instead of "μηδενὶ τῷ Β τὸ ὑπάρχειν", "μηδενὶ τῶν Β τὸ A ὑπάρχειν" (Bekker 25a16-17). Tell me if you correct these, otherwise I will not bother telling you about these errors anymore.

**Comment by lcerrato** [comment]
@bazzakoni 
Thank you for this. 
Issues within the same text may be added to any existing issue to simplify and streamline pull requests.
I do not see μηδενὶ **τῶν** Β in this passage, but perhaps I am missing it? I do see a second missing alpha.

**Comment by lcerrato** [comment]
@bazzakoni 
Ah, I see. The Ross edition uses **μηδενὶ τῷ** in an instance where the Bekker edition has **μηδενὶ τῶν**, but this appears to be a variant rather than an error.
