### ISSUE TITLE
Extra files for "Contents" in Eusebius, tlg2018/tlg012a.opp-grc1, tlg020a.opp-grc1, and tlg021a.opp-grc1

### ISSUE THREAD

**Issue by jduff-chs** [OpenGreekAndLatin/First1KGreek#269]
Each of these files is a table of contents for the main text - e.g. 012a lists the contents of 012, etc. Each is a book from the Eusebius Werke series, published in Leipzig, and each of these tables is in these texts, just as it is preserved in the XML. It's unclear if they are portions of the actual text, but they seem to be an editorial addition. Should they be merged into the main files, left as they are, or deleted?

Here's an example of the XML from one of these tables, 20a.

``` xml
<div type="textpart" subtype="book" n="1">
<pb n="2"/>
<head>ΕΙΣ TON BION
TOY MAKAPIOY ΚΩΝΣΤΑΝΤΙΝΟΥ
ΒΑΣΙΔΕΩΣ</head>

<pb n="3"/>
<p>Kεφίλαια τοῦ κατὰ θεὸν
βίου τοῦ μακαρίου Κωνσταντίνου βασιλέως.
λόγος ᾱ.</p>
<p>ά. Προοίμιον περὶ τῆς Κωνσταντίνου τελευτῆς.</p>
<lb n="5"/> <p>β΄. Περὶ υἱῶν αὐτοῦ βασιλευσάντων. Ἔτι προοίμιον.</p>
<p>γ΄. Περὶ θεοῦ τιμῶντος εὐσεβεῖς βασιλεῖς καὶ ἀπολλύντος τυράννους.</p>
<p>δ΄. Ὅτι ὁ θεὸς Κωνσταντῖνον ἐτίμησεν.</p>
<p>έ. Ὅτι δὲ ὑπὲρ τὰ ἑξήκοντα.</p>
<lb n="10"/> <p>ς΄. Ὅτι θεοῦ μὲν δοῦλος ἦν ἐθνῶν δὲ νικητής.</p>
<p>ς΄. Πρὸς Κῦρον τὸν Περςῶν βασιλέα καὶ Ἀλέξανδρον τὸν Μακεδόνων σύγκρισις.</p>
<p>ή. Ὅτι τῆς οἰκουμενης πάσης σχεδὸν ἐκράτησεν.</p>
<p>θ΄. Ὅτι υἱὸς βασιλέως εὐσεβὴς καὶ υὐοῖς βασιλεῦσι κατέλιπε τὴν
<lb n="15"/> ἀρχήν.</p>
<p>ί. Περὶ τοῦ καὶ ἀναγκαίαν εἶναι καὶ ψυχωφελῆ τὴν ἱστορίαν ταύτην.</p>
<p>ιά. Ὅτι μόνας τὰς Κωνσταντίνου νῦν ἱστόρησε θεοφιλεῖς πράξεις.</p>
<p>ιβ΄. Ὅτι ὡς Μωϋςῆς ἐν οἵκοις τυράννων ἀνετάφη Κωνσταντῖνος.</p>
<p>ιγ΄. Περὶ Κωνσιταντίου τοῦ πατρὸς αὐτοῦ μὴ ἀνασχομένου τῶν περὶ</p>
```

Furthermore, according to the precedent set by 012 and 020, in 021 the contents should be listed as 021a.opp-grc1, and the text as 021.opp-grc1, but instead the text is labeled 021a.opp-grc2, as if it were a second edition of the table of contents. This seems like it should be resolved.

**Comment by jduff-chs** [comment]
Below is a screenshot of this same tables of contents within the edition in question.

![screen shot 2016-06-17 at 2 40 25 pm](https://cloud.githubusercontent.com/assets/19731635/16161061/8f834290-3499-11e6-8a14-8edfebddae66.png)

**Comment by sonofmun** [comment]
These are almost certainly a later addition, i.e., I don't think Eusebius probably put his own table of contents in. That being said, I don't know if we can be sure of this. And, if we can't, this should probably be integrated into the main text and not in a different file.
As for the work IDs, tlg012a would not be another edition of tlg012. That would be marked up differently, e.g., tlg012.opp-grc1 and tlg012.opp-grc2. tgl012a and tlg012 would be completely different works. In any case, what is important is what the Perseus catalog or the TLG catalog says about these works. None of tlg012(a), tlg021(a), or tlg020(a) has an entry in the Perseus Catalog. According to the TLG catalog, tlg012 should be "In cantica canticorum interpretatio", tlg020 should be the "Vita Constantini"(which it appears is correct) and tlg021 should be "Constantini imperatoris oratio ad coetum sanctorum".
So, in the end, I think I would integrate the TOC for all of these works into the file tlg2018.tlg012.opp-grc1, etc. (i.e., the filename without the "a") and label their citation unit as n="TOC" and it should be at the same citation level as the citations that it contains, e.g., if it is the TOC of a book that contains `<div type="textpart" subtype="section">` tags, then it should be contained within a `<div type="textpart" subtype="section" n="TOC">` tag.
I hope that makes sense.
