### ISSUE TITLE
(tlg0061) new work Pseudo-Lucian

### ISSUE THREAD

**Issue by gregorycrane** [OpenGreekAndLatin/First1KGreek#2745]
I bumped into a blog that turns out to be by Neven (filologanoga@gmail.com)
https://nevenjovanovic.github.io/2018/11/03/lucian/.

He points out that there is no open edition of Pseudo-Lucian (tlg0061). This seems still to be true. If so, its a great job, finite and of great interest, with good printed editions.

**Comment by AlisonBabeu** [comment]
hi @gregorycrane just copying here what I sent by email: 

So we didn't miss Pseudo-Lucian in the sense that it is on the First1K data entry list (lines 645-652), it just looks like it wasn't one of the authors/texts that was done in one of our various data entry sprints the last few years.

**Comment by lcerrato** [comment]
See also https://trello.com/c/65PND36c/327-pseudo-lucian-tlg0061

**Comment by lcerrato** [comment]
@AlisonBabeu 
what is the workgroup for tlg0061? The catalog does not designate Pseudo-Lucian versus Lucian.

**Comment by AlisonBabeu** [comment]
hi @lcerrato I would use Pseudo-Lucian in all honesty. We have been using Pseudo-Author name for all the author pseudo authors in the collection.

**Comment by lcerrato** [comment]
Some notes: punctuation was not captured well (many commas are periods, many semicolons not captured, etc.; strange theta appears, most capital letters not captured well).

**Comment by lcerrato** [comment]
Done all works in volumes 1 and 3. Need to run volume 2.
