### ISSUE TITLE
(tlg2042.tlg009.opp-grc1:3.2) trailing periods instead of gap tags

### ISSUE THREAD

**Issue by gcelano** [OpenGreekAndLatin/First1KGreek#2817]
There are many suspicious dots:

```
<milestone unit="altnumbering" n="141"/> γὰρ »τὰ τέκνα τῆς ἐρήμου μᾶλλον ἢ τῆς
                            ἐχούσης τὸν ἄνδρα( καὶ ἀπειλεῖ αὐτοῖς, οἷς οὐ γέγονεν ἔρημος οὐδὲ γῆ
                            κεχερσωμένη, λέγων· ἐγὼ μὲν οὐ γέγονα ὑμῖν »ἔρημος« οὐδὲ »γῆ
                            κεχερσωμένη«, ὑμεῖς δὲ εἰρήκατε· »οὐ κυριευθησόμεθα, οὐχ ἥξομεν πρός σε
                            ἔτι«. ἆρα εἰρήκασιν οἱ υἱοὶ Ἰσραὴλ ἀπονενοημένως <lb n="20"/> κατὰ τὴν
                            λέξιν· »οὐ κυριευθησόμεθα« . . . . . . . . . . . . . . .
                            ......................................................................
                            ......................................................................
                            ......................................................................
                            ......................................................................
                            ......................................................................
                            ......................................................................</p>
                        <note type="footnote">4f. Vgl. Hebr. 5, 14. — 15 Jes. 54, 1 (Gal. 4,
                            27).</note>
                        <note type="footnote">4 κατὰ τὸ σῶμα] fast unleserlich (vgl. TU NF 1, 3, 16
                            Anm. 4) in S, ätigt durcb C: ἐν τῷ σωματικῷ | 5 ἔχει S | 10 αὐτὸς C
                            αὐτοῖς S | 20 κυριευθησόμεθα. ὁμιλία γ΄ S. Dass die Homilie verstümmelt
                            ist, beweist abgesehn von das plötzliche Abbrechen und das Fehlen der
                            Schlussdoxologie. In C Frgm. 67 folgt auf ἄνδρα Ζ. 16) noch: Φησὶν οὖν
                            ἐντρεπτικῶς· μὴ τοῖς εἰδώλοις ὁμοίως ἀνόνητος αὐτοῖς γέγονα, οῠ χάριν
                            τὴν ἐμὴν ἀπέδρασαν δεσποτείαν; καίτοι καὶ ἀποστάντες ἐμοῦ κόσμου καὶ

```

**Comment by mgbilby** [comment]
I'd recently found something similar in tlg2042.tlg008, a text on which I've done more extensive research. The OW editors at the time tended to represent line breaks in the manuscripts with these running ellipses.

![Orig_frag](https://github.com/user-attachments/assets/86388f6e-394a-4968-b395-201beaffe944)
![BNF_supp_gr_0534_5r_Origen_Eux_Lk11 1_lacuna_inverted](https://github.com/user-attachments/assets/1d453a1c-5fc0-4a33-8912-92de3b81528f)
![Trin_B 8 10_216v_Origen_Eux_Lk11 1_lacuna](https://github.com/user-attachments/assets/dff3abee-8ff4-46c8-a9c4-0bfcbf386ca1)
![BNF_supp_gr_0534_5r_Origen_Eux_Lk11 1_lacuna](https://github.com/user-attachments/assets/e225d10c-0aa1-4aba-abec-3ed8ec17c6c5)

**Comment by mgbilby** [comment]
![2024-12-17_Origen_orat_tlg2042 tlg009_OW2_p302png](https://github.com/user-attachments/assets/ab52cb4c-b8e9-4cad-809a-31e8df15cbaa)

**Comment by lcerrato** [comment]
@mgbilby @gcelano 
Yes, there are numerous examples of this. 
Perseus practice is to tag these `<gap reason="lost" rend=" . . . . . . . . . . . . "/>`
I don't think that OGL texts adopted this for all texts.

**Comment by gcelano** [comment]
Yes, the use of the element `gap` is advisable in all these cases, otherwise those points might be treated as regular tokens. In my automated system, for example, I got weird syntactic trees.
