### ISSUE TITLE
Encode critical punctuation and text reuse citations in tlg2042.tlg005.opp-grc1

### ISSUE THREAD

**Issue by jduff-chs** [OpenGreekAndLatin/First1KGreek#296]
All < and > need to be encoded as `<add></add>`. Make sure to check xml carefully against source. See comments in #286.

Text reuse should be encoded as `<quote corresp="URN">quoted text</quote>`, as described in the comments in #201.

**Comment by planatheisa** [comment]
Quotes are here given as: 
`<cit>
                            <bibl n="John 1.1">1, 1.</bibl>
                            <quote>Ἐν ἀρχῇ ἦν ὁ λόγος.</quote>
                        </cit>`

would it be correct to change them to:
`<quote corresp="urn:cts:greekLit:tlg0031.tlg004:1.1">
 <p>...</p>
</quote>`

or do i just insert the corresp-attribute into the existing quote-tag? @jduff-chs @sonofmun @annettegessner

**Comment by sonofmun** [comment]
I like your first solution better. And for "John 1.19-20", it should be @corresp="urn:cts:greekLit:tlg0031.tlg004:1.19-1.20". Make sure to mention all parts of the citation unit on both sides of the hyphen. I.e., don't so "1.19-20" but "1.19-1.20".
