### ISSUE TITLE
Epidoc Compliance questions

### ISSUE THREAD

**Issue by annettegessner** [OpenGreekAndLatin/First1KGreek#5]
(same text as in the mail I sent)

Hi Thibault,

I have some Epidoc related questions, Matt and I couldn't answer.
I have been working on the files of the First 1k Greek corpus, which are not Epidoc compliant yet. You can find my changes on branch "replacetest" here:
https://github.com/OpenGreekAndLatin/First1KGreek/tree/replacetest/split/Not_Epidoc_Compliant

My questions are the following:

1) Do we have to replace the “speaker-tag” 
`<sp>`
by
`<div type=”textpart” subtype=”speaker”>`
or can we keep it like this?

2) What to do with:
&Perseus.publish;
Do we need this info somewhere or can we just delete it?
(e.g. in tlg0555.001.xml)

3) There are some tags "not allowed":
`<opener>` (e.g. in tlg1205.tlg001)
and
`<argument>` (e.g. in tlg2115.tlg060)
What to do with them?

Hope you can help here.
Thanks in advance,

Annette

**Comment by PonteIneptique** [comment]
1. Use `said` if I remember well, https://github.com/PerseusDL/tei-conversion-tools/wiki/Speaker-to-Said
2. Keep it and replace it with the right value, you can found DTDs here https://github.com/PerseusDL/tei-conversion-tools/tree/master/dtd
3. You can use div for them I assume. Could you make link to file when you are quoting something like that ? :)

Remember to check tei-conversion-tools wiki for specific question, in the end, I am no Epidoc master

**Comment by annettegessner** [comment]
@PonteIneptique about question 3):

There are some instances of letters starting of with an "opener" containing the date and/or the salutation of the letter like
[canonical-latinLit/phi0478.phi003.perseus-lat1.xml](https://github.com/PerseusDL/canonical-latinLit/blob/5d75f4277dca1289a5fd21b8cf36172feb6239bc/data/phi0478/phi003/phi0478.phi003.perseus-lat1.xml)
`<opener>
	        <dateline>Scr. in. anno 690 (64).</dateline>
	        <salute>QVINTVS MARCO FRATRI S. D.</salute>
</opener>`

or 
[First1KGreek/tlg1205.tlg001.perseus-grc2](https://github.com/OpenGreekAndLatin/First1KGreek/blob/master/Not_Epidoc_Compliant/tlg1205/tlg001/tlg1205.tlg001.perseus-grc2.xml)
`<div type="edition" n="">
<pb xml:id="v.1.p.9"/>
<head>ΑΘΗΝΑΓΟΡΟΥ
ΑΘΗΝΑΙΟΥ ΦΙΛΟΣΟΦΟΥ ΧΡΙΣΤΓΑΝΟΥ
ΠΡΕΣΒΕΙΑ ΠΕΡΙ ΧΡΙΣΤΙΑΝΩΝ.<bibl n="Owen 1876 New York"/></head>
<opener><salute>Αὐτοκράτορσιν Μάρκῳ Αὐρηλίῳ Ἀντωνίνῳ καὶ Λουκίῳ
Αὐρηλίῳ Κομμόδῳ, Ἀρμενιακοῖς, Σαρματικοῖς,
τὸ δὲ μέγιστον Φιλοσόφοις.</salute></opener>
<div type="textpart" subtype="chapter" n="1">`

Do we want to have those tagged? If not, we could just turn them into a title or simple <ab>. If yes how do we do this, when the tags "opener" and "salute" aren't allowed in EpiDoc?

(Please let me know, how to handle questions like this! I didn't find anything in the EpiDoc guidelines. Whom can I ask? Should I post my question somewhere else like in the tei-conversion-tools repository?)

**Comment by annettegessner** [comment]
also about question 3):

I would suggest replacing the tag "argument" in [tlg2115.tlg060](https://github.com/OpenGreekAndLatin/First1KGreek/blob/master/Not_Epidoc_Compliant/tlg2115/tlg060/tlg2115.tlg060.perseus-grc1.xml) and [tlg0555.002](https://github.com/OpenGreekAndLatin/First1KGreek/blob/master/Not_Epidoc_Compliant/tlg0555/tlg002/tlg0555.002.xml) with `<div type="textpart" subtype="chapter" n="argument">`, because these sections are not contained in a div-tag yet and contain some kind of table of content for the (part of the) work.

**Comment by PonteIneptique** [comment]
I have no idea, sorry. I am not an Epidoc person.

**Comment by annettegessner** [comment]
moved task of changing speaker to said to issue #71

**Comment by sonofmun** [comment]
@annettegessner I moved things like this into @subtype="chapter" (or whatever the correct name is for that level) @n="toc". If it is the TOC for a chapter, then it should be the @subtype of whatever the children of the chapter are. E.g., if the citation scheme is book, chapter, section, then the @subtype for the TOC of a book would be "chapter", of a chapter a "section". Does that make sense?

**Comment by annettegessner** [comment]
You mean the "argument"-question, Matt? Yes, "toc" should makes sense and the level matches of course the work, We can rename it, if you want.

**Comment by annettegessner** [comment]
moved the "opener" and "saluation" question to issue #72, so this one can be closed when merging PR #70
