### ISSUE TITLE
Separate English from Greek in tlg2018.tlg002.opp-grc3.xml

### ISSUE THREAD

**Issue by sonofmun** [OpenGreekAndLatin/First1KGreek#716]
The English should go in its own file, tlg2018.tlg002.opp-eng1.xml, in the same folder. Don't forget to also change the `__cts__.xml` file.

**Comment by brittanyhardy** [comment]
Can we close this issue since it is a duplicate of a closed issue, or is there something else that can be done?

**Comment by sonofmun** [comment]
It looks like the file has been separated, so I will close the issue.
