### ISSUE TITLE
tlg0555.tlg004b.perseus-grc1.xml Need to be merged with the first part

### ISSUE THREAD

**Issue by sonofmun** [OpenGreekAndLatin/First1KGreek#75]
This file only represents books 7-8 of Clement of Alexandria's _Stromata_. It needs to be brought together with the first 6 books.

**Comment by annettegessner** [comment]
There is only one file now, called tlg0555.tlg004b.opp-grc1.xml, containing book 7 and 8 of the Stromata. Issue not relevant anymore.
