### ISSUE TITLE
tlg1205.tlg001.perseus-grc2 has milestones

### ISSUE THREAD

**Issue by sonofmun** [OpenGreekAndLatin/First1KGreek#80]
The sections are in milestones instead of divs

**Comment by planatheisa** [comment]
Pagenumbers appear in form: <pb xml:id="v.1.p.12"/> instead of <pb n="12"/>. Is this OK or should I change it?

**Comment by annettegessner** [comment]
I don't think it matters too much, since we don't (or should not) use the page numbering, but since it's an easy fix, I would change them to the way we'd expect them to be, so get rid of the `v.1.p.` and I'll merge it.

**Comment by annettegessner** [comment]
About writing XML in GitHub commentary: You have to wrap your tags in "´" signs (=Akut), or else it won't show up here (I changed it in your last commentary).

**Comment by planatheisa** [comment]
OK

**Comment by planatheisa** [comment]
I can't revert the commit. @annettegessner  Can you merge it and I will commit a second time?

**Comment by annettegessner** [comment]
ok

**Comment by annettegessner** [comment]
I merged it. In theory, it should be able to do a second commit. We should really get you on board with using the command line instead of GitHub Desktop.

**Comment by planatheisa** [comment]
Yes, maybe... Generally I can revert commits but I got an error message.

**Comment by sonofmun** [comment]
Don't worry about reverting commits. Just make more changes and do a new commit. This will overwrite your previous one.
