### ISSUE TITLE
tlg0555.tlg002.opp-grc1.xml milestone

### ISSUE THREAD

**Issue by sonofmun** [OpenGreekAndLatin/First1KGreek#82]
subsections are in milestones instead of divs

**Comment by planatheisa** [comment]
Actually there are sections and subsections within milestone-tags. Changing both to divs would increase the CTS levels to four. Should I really do this? Also, both section and subsection are added by the editors, not a structure within the text itself. So maybe we could just leave it like that? @annettegessner  @sonofmun

**Comment by annettegessner** [comment]
I am fine with that. We really don't need the tiny subsections and also the sections, which are numbered consecutively, which tends to be a "bad sign", are not really necessary. If the scan suggests that book and chapter is the important segmentation, let's keep it that way. @sonofmun ?

**Comment by sonofmun** [comment]
I would agree, especially if the numbering of the sections crosses the borders of the citation levels higher up on the tree, e.g., if the last section of chapter 1 is 29 and the first of chapter 2 is 30.

**Comment by annettegessner** [comment]
That's what I meant by "sections are numbered consecutively", sorry for being a bit unclear.

Ok, Tabea, you can leave it like that!

**Comment by sonofmun** [comment]
I figured that was what you meant, I just wanted to be clear that I understood it as well.

**Comment by planatheisa** [comment]
The header still looks different from most other ones. I added a reference with a link to a scan.

**Comment by annettegessner** [comment]
We will have to figure out a way to check all the headers at some point. For now please continue adding the link to a scan, if you found one like this:
```xml
 </monogr>
<ref target="linktoscan">e.g. Internet Archive or Google Books</ref>
          </biblStruct>
```

**Comment by annettegessner** [comment]
Just saw, you did it absolutely correctly already. Thanks!
