### ISSUE TITLE
tlg0082.tlg004.1st1K-grc1.xml is in an incorrectly named directory

### ISSUE THREAD

**Issue by AlisonBabeu** [OpenGreekAndLatin/First1KGreek#839]
The work file for tlg0082.tlg004 has been placed in the subdirectory for tlg0082.tlg001, from looking at the path here: https://raw.githubusercontent.com/OpenGreekAndLatin/First1KGreek/master/data/tlg0082/tlg001/tlg0082.tlg004.1st1K-grc1.xml/

**Comment by sonofmun** [comment]
This is true but it is fixed in a pull request that is waiting to be merged #831
