### ISSUE TITLE
tlg0530/tlg035/tlg0530.tlg035.1st1K-grc1.xml--wrong work ID

### ISSUE THREAD

**Issue by AlisonBabeu** [OpenGreekAndLatin/First1KGreek#908]
After looking at this text [De Venereis](https://github.com/OpenGreekAndLatin/First1KGreek/blob/master/data/tlg0530/tlg035/tlg0530.tlg035.1st1K-grc1.xml#L56), which was included under [Pseudo-Galen](https://www.graeco-arabic-studies.org/fileadmin/user_upload/texts.xml/Galen-Gr_049.xml) at the Mellon Graeco Arabic corpus, it appears that the TLG includes this under the main work ID of Galen, and has assigned it tlg0057.tlg035. The text found in this XML file is identical with the text of that work found online, although from different editions. 

In addition, tlg0530.tlg035 is used for another Pseudo Galen work, De urinis ex Hippocrate, Galeno et aliis quibusdam, that we do not have any versions of, so we will definitely want to reassign the work ID for this edition I think to tlg0057.tlg035. Also, it appears that the final URN for this edition should also be tlg0530.tlg035.1st1K-grc2, because according to the 1st 1K spreadsheet picklist, a version of this work has been sent to DDD for data entry.

**Comment by sonofmun** [comment]
Do you want to change it, Alison, or should @planatheisa or me do it? And when you list the final target URN at the end, should that be tlg0057.tlg035.1st1K-grc2? Or are you referring there to an edition of De urinis?

**Comment by AlisonBabeu** [comment]
I would change it, but I don't have the authority to delete or add files to this repository, so I"m not sure how I could rename this file and move it. And in terms of what we sent to DDD, we sent them an edition of De Venereis, not De Urinis.

**Comment by sonofmun** [comment]
You could change it on your fork of the repository and do a pull request, just like you do for any change.
And as far as the URN, I just wanted to make sure I understood. So the final URN that we want is tlg0057.tlg035.1st1K-grc2, right?

**Comment by AlisonBabeu** [comment]
Yes, that final URN is correct. And you are right I'm realizing, I could
change the URN on my fork and do a pull request. I'm still getting the hang
of this alas.
