### ISSUE TITLE
tlg0627.tlg016.1st1K-grc1.xml contains only Book I

### ISSUE THREAD

**Issue by AlisonBabeu** [OpenGreekAndLatin/First1KGreek#939]
So the full text of the work tlg0672.tlg016 was split between volumes 5 and volume 9 of this edition series. The scanned text of the second book of Prorrheticon is available on pages 6-74 of volume 9 and is available [here](http://www.biusante.parisdescartes.fr/histoire/medica/resultats/?p=10&cote=34859x09&do=page) 

I was wondering if we should try and OCR and add Book II.

**Comment by LindaMcNulty** [comment]
This looks like it has also been updated to include Book II now!
