### ISSUE TITLE
tlg0627.tlg023.1st1K-grc1.xml contains only book 1

### ISSUE THREAD

**Issue by AlisonBabeu** [OpenGreekAndLatin/First1KGreek#943]
While the header for this work accurately reflects that the current edition on [Github](https://github.com/OpenGreekAndLatin/First1KGreek/blob/master/data/tlg0627/tlg023/tlg0627.tlg023.1st1K-grc1.xml) only contains Book I, I was wondering if we had any plans to add Books 2-3 of this work, both of which are available in Volume 7:8‑114‑ 118‑160‑ of the same series, available here: http://www.biusante.parisdescartes.fr/histoire/medica/resultats/?cote=34859x07&do=chapitre

**Comment by AlisonBabeu** [comment]
It also appears that Books II and Book III of this work De Morbis are also available at the Digital Corpus for Graeco-Arabic Studies, https://www.graeco-arabic-studies.org/fileadmin/user_upload/texts.xml/Hipp-Gr_048.xml and https://www.graeco-arabic-studies.org/fileadmin/user_upload/texts.xml/Hipp-Gr_049.xml

**Comment by LindaMcNulty** [comment]
Looks like books 2-3 have since been added to our files. Can we close this issue?
