### ISSUE TITLE
tlg1724,tlg001.1st1K-grc1 contains other works

### ISSUE THREAD

**Issue by AlisonBabeu** [OpenGreekAndLatin/First1KGreek#954]
So while the commit history for this work [here](https://github.com/OpenGreekAndLatin/First1KGreek/commit/59e459d71d03b95e04db0fb50934f2203b41d4dd) notes that only part of the work of Theon of Smyrna is here, this file also includes the entire text of the two works of Autolycus as well as one work by Nicomachus of Gerasa  and at least one other work, all of which do seem to have made it to the correct repositories.

The work by Theon of Smyrna only begins at line 12210 and continues to the end of the XML file. There is also not _cts.xml file for this work as well.

**Comment by brittanyhardy** [comment]
Has this issue been resolved? The current edition of the file contains 6722 lines, the body of which appears to align with the Archives.org version of Theon of Smyrna. Should we close this issue?

**Comment by sonofmun** [comment]
I appears that this problem was corrected about 3 months ago. Closing the issue.
